__author__ = 'E. Marinetto'

from xml.etree import ElementTree
from Plus import PrettyXMLPrint

class Device(object):

    """
    Class that represents a Device in Plus Library

    A Device can be:
        - US Probe
        - Tracker System
        - Data Processor
    """

    def __init__(self):
        """
        Void Initialization
        """
        self.id = 'UnknownDeviceId'
        """:param id: String with the id name for the device """
        self.codeXmlDevice = self.generatexml()
        """:param codeXmlServer:  XML code for Device """


    def generatexml(self):
        """
        Get the code configuration for the PlusServer app
        """
        codeXmlDevice = ElementTree.Element('Device')
        codeXmlDevice.set('Id', self.id)

        comment = ElementTree.Comment('Generated by Plus Module (Marinetto)')
        codeXmlDevice.append(comment)

        return codeXmlDevice

    def prettyprint(self):
        print PrettyXMLPrint.prettify(self.codeXmlDevice)


