__author__ = 'E. Marinetto'
# Importing need files
from Plus import Device as Plus
from xml.etree import ElementTree


class USProbe(Plus.Device):

    """
    Class that represents a US Device in Plus Library

    A Device can be:
        - Interson USB System
    """

    def __init__(self):
        """
        Void Initialization
        """
        self.id = 'VideoDevice'
        self.codeXmlDevice = self.generatexml()

    def generatexml(self):
        """
        Get the code configuration for the PlusServer app
        """
        codeXmlDevice = ElementTree.Element('Device')
        codeXmlDevice.set('Id', self.id)

        comment = ElementTree.Comment('Generated by Plus Module (Marinetto)')
        codeXmlDevice.append(comment)

        return codeXmlDevice